user nginx;

worker_processes auto;

error_log /var/log/nginx/error.log warn;

pid /var/run/nginx.pid;


events {

    worker_connections 1024;

}


http {

    include /etc/nginx/mime.types;

    default_type application/octet-stream;


    access_log /var/log/nginx/access.log;


    sendfile on;

    keepalive_timeout 60;

    gzip on;

    server {

        listen 80;

        server_name localhost;


        # Vue frontend
        root /app/frontend/dist;

        index index.html;


        # Vue routes
        location / {

            try_files $uri $uri/ /index.html;

        }


        # Laravel API
        location /api {

            root /app/backend/public;

            try_files $uri $uri/ /index.php?$query_string;

        }


        # PHP-FPM
        location ~ \.php$ {

            root /app/backend/public;


            fastcgi_pass backend:9000;

            fastcgi_index index.php;

            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        }


        # Security
        location ~ /\. {

            deny all;

        }

    }

}
