[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:queue-worker]
command=php /app/artisan queue:work --sleep=1 --tries=3
autostart=true
autorestart=true
stdout_logfile=/var/log/queue.log
stderr_logfile=/var/log/queue-error.log

[program:kafka-consumer]
command=php /app/artisan kafka:billing-consume
autostart=true
autorestart=true
stdout_logfile=/var/log/kafka.log
stderr_logfile=/var/log/kafka-error.log

[program:payment-consumer]
command=php /app/artisan kafka:payment-consume
autostart=true
autorestart=true
stdout_logfile=/var/log/payment.log
stderr_logfile=/var/log/payment-error.log

[program:notification-consumer]
command=php /app/artisan kafka:notification-consume
autostart=true
autorestart=true
stdout_logfile=/var/log/notification.log
stderr_logfile=/var/log/notification-error.log

[program:service-activated-consumer]
command=php /app/artisan kafka:service-activated-consume
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/service-activated.log
stderr_logfile=/var/log/service-activated-error.log
